# Generated by Django 4.0.1 on 2022-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=255)),
                ('back', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=10)),
                ('starred', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('state', models.CharField(default='Unrevealed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_cards', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_visited', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('color', models.CharField(max_length=10)),
                ('starred', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spend', models.FloatField(default=0.0)),
                ('number_correct_answers', models.IntegerField(default=0)),
                ('number_studied_cards', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('number_decks', models.IntegerField()),
                ('number_cards', models.IntegerField()),
            ],
        ),
    ]
